PRAGMA page_size = 4096;

CREATE TABLE pokemon (
    id          INTEGER PRIMARY KEY,
    name        TEXT,
    type        TEXT,
    description TEXT
);

INSERT INTO pokemon VALUES (1,  'Articuno',    'ice/flying',       'Legendary bird of Kanto. Freezes water vapor in the air into snow as it flies through wintry skies.');
INSERT INTO pokemon VALUES (2,  'Zapdos',      'electric/flying',  'Legendary bird said to live in thunderclouds. Gains power when struck by lightning during storms.');
INSERT INTO pokemon VALUES (3,  'Moltres',     'fire/flying',      'Legendary firebird whose feathers burn with brilliant flame. Migrates with the changing seasons.');
INSERT INTO pokemon VALUES (4,  'Mewtwo',      'psychic',          'Genetically engineered Pokemon created from Mews DNA. Possesses the most savage psychic mind in existence.');
INSERT INTO pokemon VALUES (5,  'Mew',         'psychic',          'Mythical ancestor of all Pokemon. Contains the genetic code of every species inside its tiny body.');
INSERT INTO pokemon VALUES (6,  'Raikou',      'electric',         'Legendary beast that embodies lightning. Its roar shakes the ground and triggers thunderstorms.');
INSERT INTO pokemon VALUES (7,  'Entei',       'fire',             'Legendary beast born from volcanic eruption. A new volcano erupts whenever Entei roars across the land.');
INSERT INTO pokemon VALUES (8,  'Suicune',     'water',            'Legendary beast that purifies tainted water. Runs across the world to find polluted lakes to cleanse.');
INSERT INTO pokemon VALUES (9,  'Lugia',       'psychic/flying',   'Guardian of the seas. A single flap of its wings can level skyscrapers and stir typhoon winds.');
INSERT INTO pokemon VALUES (10, 'Ho-Oh',       'fire/flying',      'Rainbow phoenix whose feathers glow in seven colors. Said to bring eternal happiness to those who see it.');
INSERT INTO pokemon VALUES (11, 'Celebi',      'psychic/grass',    'Mythical time travelling Pokemon. Forests flourish wherever this voice of the woods appears.');
INSERT INTO pokemon VALUES (12, 'Regirock',    'rock',             'Body composed of stones gathered from around the world. Recovers lost rocks during battle.');
INSERT INTO pokemon VALUES (13, 'Regice',      'ice',              'Body made of antarctic ice from the Ice Age. Surrounded by air colder than minus 200 degrees.');
INSERT INTO pokemon VALUES (14, 'Registeel',   'steel',            'Body harder than any known metal. Its body has been tempered by tens of thousands of years of pressure.');
INSERT INTO pokemon VALUES (15, 'Latias',      'dragon/psychic',   'Eon Pokemon that wraps itself in a glass-like down to refract light and change appearance.');
INSERT INTO pokemon VALUES (16, 'Latios',      'dragon/psychic',   'Highly intelligent Eon dragon. Capable of telepathic communication and folds its limbs to fly faster than jets.');
INSERT INTO pokemon VALUES (17, 'Kyogre',      'water',            'Primordial sea behemoth. Said to have raised sea levels by causing torrential rain and tsunamis.');
INSERT INTO pokemon VALUES (18, 'Groudon',     'ground',           'Primordial earth titan. Created continents by causing volcanic eruptions and droughts in ancient times.');
INSERT INTO pokemon VALUES (19, 'Rayquaza',    'dragon/flying',    'Sky high dragon that lives in the ozone layer. Stops fights between Kyogre and Groudon.');
INSERT INTO pokemon VALUES (20, 'Jirachi',     'steel/psychic',    'Wish Pokemon that awakens for seven days every thousand years. Grants any wish written on its head tags.');
INSERT INTO pokemon VALUES (21, 'Deoxys',      'psychic',          'Born from a space virus mutated by laser beams. Can transform between attack, defense, and speed forms.');
INSERT INTO pokemon VALUES (22, 'Uxie',        'psychic',          'Being of Knowledge. Said to have given humans the intelligence to improve their quality of life.');
INSERT INTO pokemon VALUES (23, 'Mesprit',     'psychic',          'Being of Emotion. Taught humans the nobility of sorrow, pain, and joy through its sleep at lake bottom.');
INSERT INTO pokemon VALUES (24, 'Azelf',       'psychic',          'Being of Willpower. Sleeps deep at the bottom of a lake to keep the world in balance.');
INSERT INTO pokemon VALUES (25, 'Dialga',      'steel/dragon',     'Temporal dragon that controls time itself. Time flows when Dialgas heart beats and stops when it sleeps.');
INSERT INTO pokemon VALUES (26, 'Palkia',      'water/dragon',     'Spatial dragon with the ability to distort space. Lives in a gap between dimensions parallel to ours.');
INSERT INTO pokemon VALUES (27, 'Heatran',     'fire/steel',       'Dwells in volcanic caves where it digs with cross-shaped feet. Boils magma into its body for heat.');
INSERT INTO pokemon VALUES (28, 'Regigigas',   'normal',           'Said to have shaped the continents by towing them with ropes. Slumbers in the deepest part of Snowpoint.');
INSERT INTO pokemon VALUES (29, 'Giratina',    'ghost/dragon',     'Banished to the Distortion World for its violence. Glides silently through alternate dimensions.');
INSERT INTO pokemon VALUES (30, 'Cresselia',   'psychic',          'Crescent moon Pokemon that emanates a veil of brilliant feathers. Brings pleasant dreams to sleepers.');
INSERT INTO pokemon VALUES (31, 'Phione',      'water',            'Mythical sea drifter. When water warms, it inflates the flotation sac on its head and travels with currents.');
INSERT INTO pokemon VALUES (32, 'Manaphy',     'water',            'Prince of the sea born from an egg deep in cold ocean trenches. Has the power to bond with any species.');
INSERT INTO pokemon VALUES (33, 'Darkrai',     'dark',             'Causes nightmares in those who sleep nearby. Only a Lunar Wing can dispel its dark abilities.');
INSERT INTO pokemon VALUES (34, 'Shaymin',     'grass',            'Gratitude Pokemon that dissolves toxins in the air. Can instantly transform polluted land into lush field.');
INSERT INTO pokemon VALUES (35, 'Arceus',      'normal',           'Said to have shaped the universe with its thousand arms. Holds a plate that changes its elemental type.');
INSERT INTO pokemon VALUES (36, 'Victini',     'psychic/fire',     'Brings victory to its trainer. Generates infinite energy from inside its body and shares it freely.');
INSERT INTO pokemon VALUES (37, 'Cobalion',    'steel/fighting',   'Has a body and heart of steel. Its glare can make even rude Pokemon obey out of pure intimidation.');
INSERT INTO pokemon VALUES (38, 'Terrakion',   'rock/fighting',    'Charged through castle walls to save Pokemon caged by humans. Its strength can break giant mountains.');
INSERT INTO pokemon VALUES (39, 'Virizion',    'grass/fighting',   'Has horns sharp as blades. Confused enemies with quick movements before slashing them down.');
INSERT INTO pokemon VALUES (40, 'Tornadus',    'flying',           'Flies through the sky at 200 mph causing massive storms. Its tail releases monstrous gusts of wind.');
INSERT INTO pokemon VALUES (41, 'Thundurus',   'electric/flying',  'Flies around firing lightning bolts from spikes on its tail. Charred landscapes mark its wandering path.');
INSERT INTO pokemon VALUES (42, 'Reshiram',    'dragon/fire',      'Vast Whiteness dragon whose fiery tail sends flames erupting. Helps those seeking truth.');
INSERT INTO pokemon VALUES (43, 'Zekrom',      'dragon/electric',  'Deep Black dragon that scorches the world with lightning. Aids those who seek to fulfill ideals.');
INSERT INTO pokemon VALUES (44, 'Landorus',    'ground/flying',    'Abundance Pokemon revered as Guardian of the Fields. Brings bountiful harvests wherever it passes.');
INSERT INTO pokemon VALUES (45, 'Kyurem',      'dragon/ice',       'Generates a strong freezing energy inside itself. Body is leaking that energy as cold air.');
INSERT INTO pokemon VALUES (46, 'Keldeo',      'water/fighting',   'Crosses the world running over the surface of water. Appears at shores with beautiful pure water.');
INSERT INTO pokemon VALUES (47, 'Meloetta',    'normal/psychic',   'Melodies sung by Meloetta have the power to make Pokemon happy or sad and control their emotions.');
INSERT INTO pokemon VALUES (48, 'Genesect',    'bug/steel',        'Ancient bug revived and modified by Team Plasma with a cannon installed on its back.');
INSERT INTO pokemon VALUES (49, 'Xerneas',     'fairy',            'Life Pokemon whose horns shine in seven colors. Can share eternal life with surrounding Pokemon.');
INSERT INTO pokemon VALUES (50, 'Yveltal',     'dark/flying',      'Destruction Pokemon. When its life ends it absorbs the life energy of every living thing nearby.');
INSERT INTO pokemon VALUES (51, 'Zygarde',     'dragon/ground',    'Order Pokemon that monitors the ecosystem. Its many cells gather to assume different forms.');
INSERT INTO pokemon VALUES (52, 'Diancie',     'rock/fairy',       'Sudden mutation of Carbink. Can produce diamonds by compressing carbon in the atmosphere between hands.');
INSERT INTO pokemon VALUES (53, 'Hoopa',       'psychic/ghost',    'Mischievous trickster that uses six rings and six giant arms to seize anything that catches its eye.');
INSERT INTO pokemon VALUES (54, 'Volcanion',   'fire/water',       'Expels internal steam with enormous force. Can erase a whole mountain with the resulting jet stream.');
INSERT INTO pokemon VALUES (55, 'TypeNull',    'normal',           'Synthetic Pokemon created to fight Ultra Beasts. Wears a heavy mask to suppress its hidden power.');
INSERT INTO pokemon VALUES (56, 'Silvally',    'normal',           'Trusted partner form of Type Null. By holding a special memory it can change type at will.');
INSERT INTO pokemon VALUES (57, 'TapuKoko',    'electric/fairy',   'Guardian deity of Melemele Island. Stores electricity in its body and unleashes it during battle.');
INSERT INTO pokemon VALUES (58, 'TapuLele',    'psychic/fairy',    'Guardian deity of Akala. Scatters glowing scales that heal the injuries of those who touch them.');
INSERT INTO pokemon VALUES (59, 'TapuBulu',    'grass/fairy',      'Guardian deity of Ulaula. Manipulates plants and vegetation to ensnare and crush its opponents.');
INSERT INTO pokemon VALUES (60, 'TapuFini',    'water/fairy',      'Guardian deity of Poni. Creates mist that purifies anything and confuses those caught within it.');
INSERT INTO pokemon VALUES (61, 'Cosmog',      'psychic',          'Nebula Pokemon believed to be from another world. Its body is gaseous and as soft as the wind.');
INSERT INTO pokemon VALUES (62, 'Cosmoem',     'psychic',          'Cocooned form weighing as much as a neutron star. Slowly absorbs light to fuel coming transformation.');
INSERT INTO pokemon VALUES (63, 'Solgaleo',    'psychic/steel',    'Known as the beast that devours the sun. Glows with an intense aura that turns night into day.');
INSERT INTO pokemon VALUES (64, 'Lunala',      'psychic/ghost',    'Beast that calls the moon. Folds its wings and gazes into another world as it absorbs starlight.');
INSERT INTO pokemon VALUES (65, 'Nihilego',    'rock/poison',      'Ultra Beast resembling a child wearing a jellyfish. Injects a toxin that drives prey into a stupor.');
INSERT INTO pokemon VALUES (66, 'Buzzwole',    'bug/fighting',     'Ultra Beast with bulging muscles. Capable of leveling mountains with a single flex of its arms.');
INSERT INTO pokemon VALUES (67, 'Pheromosa',   'bug/fighting',     'Ultra Beast of unparalleled speed and beauty. Avoids touching anything in this dimension as if afraid.');
INSERT INTO pokemon VALUES (68, 'Xurkitree',   'electric',         'Ultra Beast made of tangled wires. Plants its limbs in the ground to absorb electrical power.');
INSERT INTO pokemon VALUES (69, 'Celesteela',  'steel/flying',     'Ultra Beast shaped like a rocket. Flies by releasing flammable gas from its enormous arms.');
INSERT INTO pokemon VALUES (70, 'Kartana',     'grass/steel',      'Origami Ultra Beast as sharp as a sword. A single swing can fell a colossal tree in one stroke.');
INSERT INTO pokemon VALUES (71, 'Guzzlord',    'dark/dragon',      'Ultra Beast that gluttonously eats anything in sight. No droppings have ever been observed.');
INSERT INTO pokemon VALUES (72, 'Necrozma',    'psychic',          'Light eater that came from another world. Fires laser beams from its prism shaped body.');
INSERT INTO pokemon VALUES (73, 'Magearna',    'steel/fairy',      'Mechanical Pokemon built five hundred years ago. Reads emotions and shares them with the world.');
INSERT INTO pokemon VALUES (74, 'Marshadow',   'fighting/ghost',   'Hides in the shadows of others and mimics their movements. Considered a phantom by most people.');
INSERT INTO pokemon VALUES (75, 'Poipole',     'poison',           'Friendly Ultra Beast that emits poisonous fluid from needles on its head. Communicates by gestures.');
INSERT INTO pokemon VALUES (76, 'Naganadel',   'poison/dragon',    'Evolved Poipole that stores poison in its abdomen. Fires bursts of glowing toxic liquid.');
INSERT INTO pokemon VALUES (77, 'Stakataka',   'rock/steel',       'Ultra Beast resembling a stone fortress. Made of small lifeforms that stack together in battle.');
INSERT INTO pokemon VALUES (78, 'Blacephalon', 'fire/ghost',       'Clown like Ultra Beast that detonates its own head. The explosion steals vitality from witnesses.');
INSERT INTO pokemon VALUES (79, 'Zeraora',     'electric',         'Generates plasma from all four paws. Runs faster than lightning by riding the electricity it makes.');
INSERT INTO pokemon VALUES (80, 'Meltan',      'steel',            'Dissolves metals with acid produced in its mouth. Absorbs the resulting iron particles to feed itself.');
INSERT INTO pokemon VALUES (81, 'Melmetal',    'steel',            'Existed only in ancient times. Forges its body by attracting metallic objects with magnetic force.');
INSERT INTO pokemon VALUES (82, 'Zacian',      'fairy',            'Wields a brilliant blade in its mouth. Once revered as a deity for slicing down anything in its path.');
INSERT INTO pokemon VALUES (83, 'Zamazenta',   'fighting',         'Bears an indestructible shield of black metal. Earns trust by repelling attacks alongside warriors.');
INSERT INTO pokemon VALUES (84, 'Eternatus',   'poison/dragon',    'Arrived on a meteor and absorbed Galars energy. Its core power can cause the Dynamax phenomenon.');
INSERT INTO pokemon VALUES (85, 'Kubfu',       'fighting',         'Brave bear that trains its mind and body. Strong emotions make the headband on its forehead glow.');
INSERT INTO pokemon VALUES (86, 'Urshifu',     'fighting/dark',    'Evolved Kubfu trained in dark martial arts. Strikes with precise blows that knock out opponents instantly.');
INSERT INTO pokemon VALUES (87, 'Zarude',      'dark/grass',       'Lives in packs deep in dense jungles. Manipulates vines on its body as if they were extra arms.');
INSERT INTO pokemon VALUES (88, 'Regieleki',   'electric',         'Composed entirely of electrical energy. The fastest Regi capable of producing enormous voltage.');
INSERT INTO pokemon VALUES (89, 'Regidrago',   'dragon',           'Sealed away in ancient times due to its terrifying power. Its body is forged from dragon energy.');
INSERT INTO pokemon VALUES (90, 'Glastrier',   'ice',              'Emits intense cold from its hooves. Said to be a vicious horse spirit returning from the underworld.');
INSERT INTO pokemon VALUES (91, 'Spectrier',   'ghost',            'Galloping ghost horse that absorbs the lifeforce of anything that meets its piercing gaze.');
INSERT INTO pokemon VALUES (92, 'Calyrex',     'psychic/grass',    'Ancient king who ruled over Galar long ago. Heals and provides blessings of bountiful harvests.');
INSERT INTO pokemon VALUES (93, 'Enamorus',    'fairy/flying',     'Brings spring blooms to Hisui. Anger and love stir storms that shape the wild landscape.');
INSERT INTO pokemon VALUES (94, 'WoChien',     'dark/grass',       'Calamity Pokemon born from tablets engraved with grudges. Sucks vitality from surrounding plant life.');
INSERT INTO pokemon VALUES (95, 'ChienPao',    'dark/ice',         'Mountain spirit that controls snow. Sword like fangs that pierce the strongest armor in a single blow.');
INSERT INTO pokemon VALUES (96, 'TingLu',      'dark/ground',      'Carries shrines on its back believed to ward off evil. Causes earthquakes by stamping the ground.');
INSERT INTO pokemon VALUES (97, 'ChiYu',       'dark/fire',        'Soul of greed dwelling in beads that absorbed magma. Generates flames that melt rocks like wax.');
INSERT INTO pokemon VALUES (98, 'Koraidon',    'fighting/dragon',  'Ancient Pokemon resembling a powerful prehistoric dragon. Roars to intimidate every challenger in sight.');
INSERT INTO pokemon VALUES (99, 'Miraidon',    'electric/dragon',  'Futuristic Pokemon shaped like a sleek dragon machine. Releases violent electric charges from its limbs.');
INSERT INTO pokemon VALUES (100,'Pecharunt',   'poison/ghost',     'Mochi shaped mythical Pokemon. Uses chains of toxic mochi to bind others and bend them to its will.');
